spring:
  application:
    name: music-quiz-rest-api
  config:
    import:
      - classpath:commons-context.yml
      - optional:classpath:commons-context-${spring.profiles.active}.yml
      - classpath:commons-observability.yml
      - optional:classpath:commons-observability-${spring.profiles.active}.yml
      - classpath:commons-security.yml
      - optional:classpath:commons-security-${spring.profiles.active}.yml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${AU_DB_MASTER_HOST}:${AU_DB_MASTER_PORT}/${AU_DB_NAME}?currentSchema=${MU_QUIZ_DB_SCHEMA}
    username: ${MU_QUIZ_DB_USERNAME}
    password: '${MU_QUIZ_DB_PASSWORD_DM}'
    hikari:
      pool-name: MuQuizMetaHikariPool
      maximum-pool-size: 8
      minimum-idle: 2
  liquibase:
    default-schema: ${MU_QUIZ_DB_SCHEMA}
    change-log: classpath:db/migration/muquiz/liquibase/db.changelog.xml
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
  docker:
    compose:
      enabled: false

server:
#  address: 0.0.0.0
  port: ${MU_QUIZ_APP_INTERNAL_PORT:8080}
  allowed-origins: ${MU_QUIZ_APP_CORS_ALLOWED_ORIGINS}

auth:
  security:
    public-paths: /health, /actuator/**
    allowed-origins: ${MU_QUIZ_APP_CORS_ALLOWED_ORIGINS}

