plugins {
    id 'art-universe.spring-boot-app'
}

archivesBaseName = 'lastfm-etl-calls-generator'

dependencies {
    implementation project(':music:data:raw:lastfm:lastfm-repositories')
    implementation project(':music:data:raw:lastfm:etl:lastfm-tasks-coordinator')

    testImplementation project(':music:data:raw:lastfm:test:lastfm-test-database-helper')
}
