plugins {
    id 'art-universe.spring-boot-app'
}

archivesBaseName = 'lastfm-etl-calls-generator'
ext.dockerImageName = 'mu-lastfm-calls-generator'

dependencies {
    implementation project(':common:config:config-client')
    implementation project(':common:commons-observability')
    implementation project(':music:data:raw:lastfm:lastfm-repositories')

    // web for actuator endpoints
    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-db-helper')
    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test')
    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-jpa')

    testRuntimeOnly 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.testcontainers:testcontainers'
}
