plugins {
    id 'art-universe.spring-boot-web-app'
}

archivesBaseName = 'lastfm-etl-rest-api'

dependencies {
    implementation project(':music:data:raw:lastfm:lastfm-models')
    implementation project(':music:data:raw:lastfm:etl:lastfm-tasks-coordinator')

    implementation 'io.micrometer:micrometer-registry-prometheus'
}
