plugins {
    id 'art-universe.spring-boot-web-app'
}

archivesBaseName = 'lastfm-etl-rest-api'
ext.dockerImageName = 'mu-lastfm-etl-rest-api'

dependencies {
    implementation project(':common:commons-observability')
    implementation project(':music:data:raw:lastfm:lastfm-repositories')

    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-context')
    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-db-helper')
    testImplementation project(':common:test:commons-test-web')
    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-jpa')

    testRuntimeOnly 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.testcontainers:testcontainers'
}
