apiVersion: v1
kind: Service
metadata:
  name: lastfm-rest-api
  namespace: mu-lastfm
  labels:
    app: lastfm-rest-api
    app.kubernetes.io/name: lastfm-rest-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: lastfm-rest-api
