plugins {
    id 'art-universe.spring-boot-web-app'
    id 'org.liquibase.gradle'
}

archivesBaseName = 'music-master-rest-api'
ext.dockerImageName = 'mu-music-data'

dependencies {
    implementation project(':common:commons-web')
    implementation project(':common:commons-security')
    implementation project(':common:commons-observability')
    implementation project(':art:data:models')
    implementation project(':music:data:semantic:semantic-models')

    implementation 'org.springframework.boot:spring-boot-docker-compose'

    runtimeOnly 'org.liquibase:liquibase-core'

    testImplementation project(':common:test:commons-test-web')
    testImplementation project(':common:test:commons-test-db')
}
