plugins {
    id 'art-universe.spring-boot-web-app'
}

archivesBaseName = 'music-master-rest-api'
ext.dockerImageName = 'mu-music-data'

dependencies {
    implementation project(':music:data:master:music-master-models')
    implementation project(':common:commons-web')
    implementation project(':common:commons-security')
    implementation project(':common:commons-observability')
    implementation project(':art:data:models')
    implementation project(':music:data:semantic:semantic-models')

    implementation 'org.springframework.boot:spring-boot-docker-compose'

    testImplementation project(':common:test:commons-test-web')
    testImplementation project(':common:test:commons-test-db')
    testImplementation project(':music:data:master:migrations:master-liquibase-resources')

    testRuntimeOnly 'org.liquibase:liquibase-core'
    testRuntimeOnly 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.testcontainers:testcontainers'
}
