apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-ui
  namespace: mu-frontend
  labels:
    app: music-ui
    app.kubernetes.io/name: music-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-ui
  template:
    metadata:
      labels:
        app: music-ui
        app.kubernetes.io/name: music-ui
    spec:
      containers:
        - name: nginx
          image: mu-music-ui:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
