apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-ui
  namespace: mu-frontend
  labels:
    app: music-ui
    app.kubernetes.io/name: music-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-ui
  template:
    metadata:
      labels:
        app: music-ui
        app.kubernetes.io/name: music-ui
    spec:
      containers:
        - name: nginx
          image: mu-music-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
          env:
            - name: MURAW_LASTFM_READ_API_HOST
              value: "localhost"
            - name: MURAW_LASTFM_READ_API_EXTERNAL_PORT
              value: "8084"
            - name: MURAW_LASTFM_WRITE_API_HOST
              value: "localhost"
            - name: MURAW_LASTFM_WRITE_API_EXTERNAL_PORT
              value: "8085"
            - name: MU_DATA_APP_HOST
              value: "localhost"
            - name: MU_DATA_APP_EXTERNAL_PORT
              value: "8082"
            - name: MU_QUIZ_APP_HOST
              value: "localhost"
            - name: MU_QUIZ_APP_EXTERNAL_PORT
              value: "8083"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
