plugins {
    id 'art-universe.java-library'
}

archivesBaseName = 'lastfm-repositories'

dependencies {
    api project(':music:data:raw:lastfm:lastfm-models')

    api 'org.springframework.data:spring-data-commons'
    api 'org.springframework.data:spring-data-jpa'

    // Brings common configuration like application-dev.yml with actuator settings
    runtimeOnly project(':common:commons-context')

    runtimeOnly 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    runtimeOnly 'io.hypersistence:hypersistence-utils-hibernate-63'
}