plugins {
    id 'art-universe.java-library'
}

archivesBaseName = 'lastfm-etl-tasks-coordinator'

dependencies {
    api 'jakarta.annotation:jakarta.annotation-api'
    api 'org.springframework.boot:spring-boot-autoconfigure'
    api 'org.springframework:spring-context'
    
    implementation 'org.slf4j:slf4j-api'
}
