plugins {
    id 'art-universe.java-library'
    id 'org.liquibase.gradle'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.liquibase:liquibase-core'
    
    runtimeOnly 'org.postgresql:postgresql'
}
