plugins {
    id 'art-universe.spring-boot-app'
}

dependencies {
    implementation project(':common:commons-web')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
    implementation 'io.micrometer:micrometer-registry-prometheus'
}
