plugins {
    id 'com.autonomousapps.dependency-analysis' version '1.28.0'
}

ext {
    lombokVersion = '1.18.30'
    liquibaseVersion = '4.15.0'
    testContainersVersion = '1.20.4'
    testContainersPostgreVersion = '1.19.6'
    openapiVersion = '2.8.6'
}

gradle.projectsEvaluated {
    tasks.register('dockerBuildAll') {
        group = 'docker'
        description = 'Build all Docker images'
        dependsOn subprojects
                .findAll { it.tasks.findByName('dockerBuild') != null }
                .collect { "${it.path}:dockerBuild" }
    }
}

allprojects {
    group = 'yurykorzun.art'
    version = '0.0.1-SNAPSHOT'
    repositories {
        mavenCentral()
        maven { url 'https://repo.spring.io/milestone' }
        maven { url 'https://repo.spring.io/snapshot' }
    }
}