rootProject.name = 'art-universe'

include 'commons'

include 'music:data:master'

include 'music:data:raw:lastfm:migrations:lastfm-liquibase-resources'
include 'music:data:raw:lastfm:migrations:lastfm-liquibase-service'
include 'music:data:raw:lastfm:lastfm-models'
include 'music:data:raw:lastfm:lastfm-repositories'
include 'music:data:raw:lastfm:lastfm-rest-api'
include 'music:data:raw:lastfm:test:lastfm-test-commons'
include 'music:data:raw:lastfm:test:lastfm-test-with-database'
include 'music:data:raw:lastfm:test:lastfm-test-database-helper'
include 'music:data:raw:lastfm:etl:lastfm-calls-generator'
include 'music:data:raw:lastfm:etl:lastfm-calls-performer'
include 'music:data:raw:lastfm:etl:lastfm-response-parser'
include 'music:data:raw:lastfm:etl:lastfm-tasks-coordinator'
include 'music:data:raw:lastfm:etl:lastfm-etl-rest-api'

include 'music:quiz'
include 'music:ui'

