rootProject.name = 'art-universe'

include 'commons'
//include 'art-universe:art-universe-messaging-impl-kafka'

include 'music'
include 'music:data:master'
include 'music:quiz'
include 'music:data:raw:lastfm-monolith'
include 'music:data:raw:lastfm:models'
include 'music:data:raw:lastfm:migrations'
include 'music:data:raw:lastfm:etl'
include 'music:data:raw:lastfm:etl-rest-api'
include 'music:data:raw:lastfm:rest-api'
include 'music:data:raw:lastfm:test-common'
include 'music:ui'
