package yurykorzun.art.universe.music.data.raw.lastfm.api.methods.common.processing.mapping.attributes;

import org.springframework.util.Assert;
import yurykorzun.art.universe.music.data.raw.lastfm.api.methods.common.dto.EntityDto;
import yurykorzun.art.universe.music.data.raw.lastfm.collectable.attribute.entity.LastfmAttribute;
import yurykorzun.art.universe.music.data.raw.lastfm.collectable.common.entity.BaseLastfmEntity;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.function.Function;

/**
 * <p>Factory for creating EntityAttributeHandler instances via reflection.</p>
 * <p>IMPORTANT! It is assumed that getters/setters are autogenerated via Lombok. If not, naming issues might occur</p>
 */
public class EntityAttributeHandlerFactory<E extends BaseLastfmEntity, D extends EntityDto<E>> {

    private final Class<E> entityClass;
    private final Class<D> dtoClass;

    /**
     * Construct factory for given entity and DTO types
     */
    public EntityAttributeHandlerFactory(Class<E> entityClass, Class<D> dtoClass) {
        Assert.notNull(entityClass, "Entity class must not be null");
        Assert.notNull(dtoClass, "DTO class must not be null");
        this.entityClass = entityClass;
        this.dtoClass = dtoClass;
    }

    /**
     * Handler when entity and DTO attribute names match
     */
    public <A> EntityAttributeHandler<E, A, D> createHandler(
        LastfmAttribute attribute,
        boolean isScoped,
        String attrName
    ) {
        return createHandler(attribute, isScoped, attrName, attrName);
    }

    /**
     * Handler when entity and DTO attribute names differ
     */
    public <A> EntityAttributeHandler<E, A, D> createHandler(
        LastfmAttribute attribute,
        boolean isScoped,
        String entityAttrName,
        String dtoAttrName
    ) {
        Function<D, A> extractor = dto -> {
            Method getter = findGetter(dtoClass, dtoAttrName);
            return invoke(getter, dto);
        };
        return createHandler(attribute, isScoped, entityAttrName, extractor);
    }

    /**
     * Handler for custom DTO value extractor
     */
    public <A> EntityAttributeHandler<E, A, D> createHandler(
        LastfmAttribute attribute,
        boolean isScoped,
        String entityAttrName,
        Function<D, A> dtoValueExtractor
    ) {
        Field field = findField(entityClass, entityAttrName);
        Method entityGetter = findGetter(field);
        Method entitySetter = findSetter(field);

        return DefaultEntityAttributeHandler.forEmbeddedAttribute(
            attribute,
            isScoped,
            e -> invoke(entityGetter, e),
            (e, val) -> invoke(entitySetter, e, val),
            dtoValueExtractor);
    }

    /**
     * Recursively finds a declared field in the class or its superclasses
     */
    private Field findField(Class<?> type, String fieldName) {
        Class<?> current = type;
        while (current != null && current != Object.class) {
            try {
                Field field = current.getDeclaredField(fieldName);
                field.setAccessible(true);
                return field;
            } catch (NoSuchFieldException e) {
                current = current.getSuperclass();
            }
        }
        throw new IllegalArgumentException(
            String.format("Field '%s' not found in %s or its superclasses", fieldName, type.getSimpleName()));
    }


    private boolean isPrimitiveBooleanField(Field field) {
        return field.getType().equals(Boolean.TYPE);
    }

    private Method findGetter(Field field) {
        String prefix = isPrimitiveBooleanField(field) ? "is" : "get";
        String methodName = String.format("%s%s" , prefix, capitalize(field.getName()));
        try {
            return field.getDeclaringClass().getMethod(methodName);
        } catch (NoSuchMethodException e) {
            throw new IllegalArgumentException(
                String.format("No getter for %s in %s", field.getName(), field.getDeclaringClass().getSimpleName()));
        }
    }

    private Method findGetter(Class<?> type, String fieldName) {
        Assert.hasText(fieldName, "Field name must not be empty");
        return findGetter(findField(type, fieldName));
    }

    private Method findSetter(Field field) {
        String capitalized = capitalize(field.getName());
        String setterName = "set" + capitalized;
        try {
            return field.getDeclaringClass().getMethod(setterName, field.getType());
        } catch (NoSuchMethodException e) {
            throw new IllegalArgumentException(
                String.format("No setter for %s in %s", field.getName(), field.getDeclaringClass().getSimpleName()));
        }
    }

    private Method findSetter(Class<?> type, String fieldName, Class<?> paramType) {
        Assert.hasText(fieldName, "Field name must not be empty");
        return findSetter(findField(type, fieldName));
    }

    @SuppressWarnings("unchecked")
    private <T> T invoke(Method method, Object target, Object... args) {
        try {
            return (T) method.invoke(target, args);
        } catch (Exception e) {
            throw new RuntimeException("Failed to invoke method: " + method, e);
        }
    }

    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }
}
