spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration,
      org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration,
      org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration,
      org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration,
      org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration,
      org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration,
      org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration
  jackson:
    serialization:
      write-dates-as-timestamps: false