apiVersion: v1
kind: Service
metadata:
  name: lastfm-calls-performer
  namespace: mu-lastfm
  labels:
    app: lastfm-calls-performer
spec:
  selector:
    app: lastfm-calls-performer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: actuator
