plugins {
    id 'art-universe.spring-boot-web-app'
}

archivesBaseName = 'spotify-rest-api'
ext.dockerImageName = 'mu-spotify-rest-api'

dependencies {
    implementation project(':common:commons-web')
    implementation project(':common:commons-observability')
    implementation project(':common:data:raw:data-raw-commons-api-client')
    implementation project(':music:data:raw:spotify:spotify-repositories')

    testImplementation project(':common:test:commons-test-web')
}
