package yurykorzun.art.universe.music.data.raw.lastfm.etl.dto;

import yurykorzun.art.universe.music.data.raw.lastfm.domain.entity.attribute.LastfmAttribute;
import yurykorzun.art.universe.music.data.raw.lastfm.domain.entity.common.LastfmEntityType;

import java.time.Instant;
import java.time.LocalDate;

/**
 * Record representing an attribute history candidate to be staged for processing.
 * <p>
 * This is a pure DTO used to pass attribute values from response parsers to the staging table.
 * <p>
 * Note: This record does not include {@code id} (generated by database sequence)
 * or {@code validTill} (implicit for current records in attribute_history_current table).
 *
 * @param apiCallId       The API call that produced this attribute value
 * @param entityType      The type of entity this attribute belongs to
 * @param entityId        The ID of the entity this attribute belongs to
 * @param attribute       The attribute type
 * @param scopeEntityType Optional scope entity type (for scoped attributes like tag relevance)
 * @param scopeEntityId   Optional scope entity ID
 * @param collectionTs    Timestamp when the value was collected
 * @param stringValue     String value of the attribute (mutually exclusive with numericValue)
 * @param numericValue    Numeric value of the attribute (mutually exclusive with stringValue)
 * @param validFrom       Date from which this value is valid
 */
public record LastfmAttributeHistoryCandidate(
        long apiCallId,
        LastfmEntityType entityType,
        long entityId,
        LastfmAttribute attribute,
        LastfmEntityType scopeEntityType,
        Long scopeEntityId,
        Instant collectionTs,
        String stringValue,
        Long numericValue,
        LocalDate validFrom
) {
    /**
     * Creates a new record with default values for collectionTs and validFrom.
     */
    public static LastfmAttributeHistoryCandidate of(
            long apiCallId,
            LastfmEntityType entityType,
            long entityId,
            LastfmAttribute attribute,
            LastfmEntityType scopeEntityType,
            Long scopeEntityId,
            String stringValue,
            Long numericValue
    ) {
        return new LastfmAttributeHistoryCandidate(
                apiCallId,
                entityType,
                entityId,
                attribute,
                scopeEntityType,
                scopeEntityId,
                Instant.now(),
                stringValue,
                numericValue,
                LocalDate.now()
        );
    }

    /**
     * Creates a new record for a string attribute with default timestamps.
     */
    public static LastfmAttributeHistoryCandidate ofString(
            long apiCallId,
            LastfmEntityType entityType,
            long entityId,
            LastfmAttribute attribute,
            String stringValue
    ) {
        return of(apiCallId, entityType, entityId, attribute, null, null, stringValue, null);
    }

    /**
     * Creates a new record for a numeric attribute with default timestamps.
     */
    public static LastfmAttributeHistoryCandidate ofNumeric(
            long apiCallId,
            LastfmEntityType entityType,
            long entityId,
            LastfmAttribute attribute,
            Long numericValue
    ) {
        return of(apiCallId, entityType, entityId, attribute, null, null, null, numericValue);
    }

    /**
     * Creates a new record for a scoped string attribute with default timestamps.
     */
    public static LastfmAttributeHistoryCandidate ofScopedString(
            long apiCallId,
            LastfmEntityType entityType,
            long entityId,
            LastfmAttribute attribute,
            LastfmEntityType scopeEntityType,
            Long scopeEntityId,
            String stringValue
    ) {
        return of(apiCallId, entityType, entityId, attribute, scopeEntityType, scopeEntityId, stringValue, null);
    }

    /**
     * Creates a new record for a scoped numeric attribute with default timestamps.
     */
    public static LastfmAttributeHistoryCandidate ofScopedNumeric(
            long apiCallId,
            LastfmEntityType entityType,
            long entityId,
            LastfmAttribute attribute,
            LastfmEntityType scopeEntityType,
            Long scopeEntityId,
            Long numericValue
    ) {
        return of(apiCallId, entityType, entityId, attribute, scopeEntityType, scopeEntityId, null, numericValue);
    }
}
