plugins {
    id 'art-universe.java-library'
}

archivesBaseName = 'lastfm-test-with-database'

dependencies {
    api project(':music:data:raw:lastfm:test:lastfm-test-commons')
    api project(':music:data:raw:lastfm:lastfm-models')
    implementation project(':music:data:raw:lastfm:migrations:lastfm-liquibase-resources')
    
    api 'org.springframework.boot:spring-boot-starter-test'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.testcontainers:testcontainers'
    api 'org.testcontainers:junit-jupiter'
    api 'org.testcontainers:postgresql'
    api 'org.liquibase:liquibase-core'
}