{
 "title": "LastFM Raw Data Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Entities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(increase(lastfm_entity_count[15m])[15m:1m])",
     "legendFormat": "{{entity_type}}"
    }
   ]
  },
  {
   "title": "Current Entity Counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lastfm_entity_count", "legendFormat": "{{entity_type}}" }
   ]
  },
  {
   "title": "Pending API calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lastfm_api_call_count{status=\"PENDING\"}",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  { "title": "API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Created API calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(sum by (api_call_type) (delta(lastfm_api_call_count[5m]))[15m:1m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "Pending API calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(delta(lastfm_api_call_count{status=\"PENDING\"}[5m])[15m:1m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "Successful API calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(increase(lastfm_api_call_count{status=\"SUCCESSFUL\"}[5m])[15m:1m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "Failed API calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(increase(lastfm_api_call_count{status=\"FAILED\"}[5m])[15m:1m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  { "title": "API Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pending API responses",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lastfm_api_response_count{status=\"PENDING\"}",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "Pending API responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(delta(lastfm_api_response_count{status=\"PENDING\"}[5m])[15m:1m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "Completed API responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg_over_time(increase(lastfm_api_response_count{status=\"COMPLETED\"}[5m])[15m:1m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "Failed API response processing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(increase(lastfm_api_response_count{status=\"PROCESSING_ERROR\"}[5m])[15m:1m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  { "title": "API Call Processing Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "API Call Generation Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(music_data_raw_lastfm_api_call_generate_seconds_sum{status=\"success\"}[5m]) / rate(music_data_raw_lastfm_api_call_generate_seconds_count{status=\"success\"}[5m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "API Call Execution Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(music_data_raw_lastfm_api_call_perform_seconds_sum{status=\"success\"}[5m]) / rate(music_data_raw_lastfm_api_call_perform_seconds_count{status=\"success\"}[5m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  },
  {
   "title": "API Response Processing Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(music_data_raw_lastfm_api_response_process_seconds_sum{status=\"success\"}[5m]) / rate(music_data_raw_lastfm_api_response_process_seconds_count{status=\"success\"}[5m])",
     "legendFormat": "{{api_call_type}}"
    }
   ]
  }
 ]
}