global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Core services
  - job_name: 'music-data'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['music-data:8080']

  - job_name: 'music-quiz'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['music-quiz:8080']

  # LastFM web services
  - job_name: 'lastfm-rest-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lastfm-rest-api:8080']

  - job_name: 'lastfm-etl-rest-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lastfm-etl-rest-api:8080']

  # LastFM ETL services (non-web apps)
  - job_name: 'lastfm-calls-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lastfm-calls-generator:8080']

  - job_name: 'lastfm-calls-performer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lastfm-calls-performer:8080']

  - job_name: 'lastfm-response-parser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lastfm-response-parser:8080']

  # Spotify ETL services
  - job_name: 'spotify-calls-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spotify-calls-generator:8080']

  - job_name: 'spotify-calls-performer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spotify-calls-performer:8080']

  - job_name: 'spotify-response-parser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spotify-response-parser:8080']

  - job_name: 'spotify-staging-applicator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spotify-staging-applicator:8080']
