apiVersion: v1
kind: Service
metadata:
  name: spotify-staging-applicator
  namespace: mu-spotify
  labels:
    app: spotify-staging-applicator
spec:
  selector:
    app: spotify-staging-applicator
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: actuator
