global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'music-data-raw-lastfm'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['music-data-raw-lastfm:8090']

#  - job_name: 'music-data'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['music-data:8091']
#
#  - job_name: 'music-quiz'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['music-quiz:8092']
