plugins {
    id 'art-universe.spring-boot-app'
}

archivesBaseName = 'lastfm-etl-calls-performer'

dependencies {
    implementation project(':music:data:raw:lastfm:lastfm-models')
    implementation project(':music:data:raw:lastfm:etl:lastfm-tasks-coordinator')

    implementation 'org.springframework.retry:spring-retry'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'com.google.guava:guava:33.4.0-jre'
}
