plugins {
    id 'art-universe.spring-boot-app'
}

archivesBaseName = 'lastfm-etl-calls-performer'
ext.dockerImageName = 'mu-lastfm-calls-performer'

dependencies {
    implementation project(':common:config:config-client')
    implementation project(':common:commons-observability')
    implementation project(':common:data:raw:data-raw-commons-api-client')
    implementation project(':music:data:raw:lastfm:lastfm-repositories')

    // web for actuator endpoints
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.retry:spring-retry'
    implementation 'com.google.guava:guava:33.4.0-jre'

    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-context')
    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-jpa')
    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-db')

    testRuntimeOnly 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.testcontainers:testcontainers'
}
