apiVersion: v1
kind: Service
metadata:
  name: spotify-calls-generator
  namespace: mu-spotify
  labels:
    app: spotify-calls-generator
spec:
  selector:
    app: spotify-calls-generator
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: actuator
