tasks.matching { it.name == 'jar' }.configureEach { enabled = true }

dependencies {
    implementation project(":art-universe:art-universe-commons")

    // messaging
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}