global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Core services
  - job_name: 'music-data'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7082']

  - job_name: 'music-quiz'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7083']

  # Master data management
  - job_name: 'music-master-semantic-analysis-trigger'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7101']

  # Semantic pipeline
  - job_name: 'semantic-analyzer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7112']

  - job_name: 'semantic-response-parser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7113']

  - job_name: 'semantic-applicator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7114']

  # LastFM web services
  - job_name: 'lastfm-rest-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7084']

  - job_name: 'lastfm-etl-rest-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7085']

  # LastFM ETL services
  - job_name: 'lastfm-calls-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7086']

  - job_name: 'lastfm-calls-performer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7087']

  - job_name: 'lastfm-response-parser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7088']

  - job_name: 'lastfm-semantic-analysis-trigger'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7215']

  # Spotify ETL services
  - job_name: 'spotify-calls-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7091']

  - job_name: 'spotify-calls-performer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7092']

  - job_name: 'spotify-response-parser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7093']

  - job_name: 'spotify-staging-applicator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:7095']
