plugins {
    id 'art-universe.java-library'
}

dependencies {
    api project(':common:commons-context')
    api 'org.springframework.boot:spring-boot-autoconfigure'
    api 'org.springframework:spring-context'
    api 'org.springframework:spring-web'
    api 'com.fasterxml.jackson.core:jackson-databind'

    implementation 'org.reflections:reflections:0.10.2'
    implementation 'jakarta.annotation:jakarta.annotation-api'
}
