spring:
  application:
    name: music-universe-raw-data-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${MURAW_LASTFM_DB_HOST:localhost}:${MURAW_LASTFM_DB_PORT:5432}/music_universe?currentSchema=mu_raw_lastfm
    username: mu_raw_lastfm_dm
    password: '${MURAW_LASTFM_DB_PASSWORD}'
    hikari:
      pool-name: MuRawLastFmHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/migration/muraw/liquibase/db.changelog.xml
  docker:
    compose:
      enabled: false

server:
  address: 0.0.0.0
  port: ${MURAW_LASTFM_APP_INTERNAL_PORT:8080}
  allowed-origins: ${MURAW_LASTFM_APP_CORS_ALLOWED_ORIGINS}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  use-management-port: true
  packages-to-scan: yurykorzun.art.universe

management:
  server:
    port: ${MURAW_LASTFM_ACTUATOR_INTERNAL_PORT:8090}
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    beans:
      access: read_only
    health:
      show-details: always
      show-components: always

scheduling:
  lastfm:
    api:
      calls:
        generate:
          fixedDelaySecs: 60
        fetch:
          fixedDelaySecs: 5
      responses:
        parse:
          fixedDelaySecs: 5
    tasks:
      poolSize: 3
      maintenance:
        cron: "0 0 8 * * *"
      tag:
        topTags:
          cron: "0 0 21 * * *"

lastfm:
  baseUrl: "http://ws.audioscrobbler.com/2.0/"
  apikey: ${MURAW_LASTFM_API_KEY}
  threshold:
    artist:
      listenersCount: 1000
    album:
      playCount: 10000
    track:
      playCount: 10000
    tag:
      usageCount: 1000
  client:
    callsPerSec: 1.0
    retry:
      max-attempts: 3
      initial-delay-ms: 500
      multiplier: 1.5
    methods:
      artist:
        getInfo:
          dueDurationDays: 7
        getSimilar:
          dueDurationDays: 28
          artistMatchThreshold: 0.2
        topTags:
          dueDurationDays: 7
          tagUsageCountThreshold: 10
        topAlbums:
          dueDurationDays: 28
          albumPlayCountThreshold: 10000
        topTracks:
          dueDurationDays: 28
          trackListenersThreshold: 1000
        search:
          artistSimilarityThreshold: 0.5
      tag:
        topTags:
          recordsLimit: 2000 # it is known that Lastfm API offset breaks after 2000th record for this method
          dueDurationDays: 7
        topArtists:
          dueDurationDays: 7
        topTracks:
          dueDurationDays: 7
          usageToPageRatio: 50000 # for each N usages of the tag, ONE 50-items api call will be generated
      track:
        getInfo:
          dueDurationDays: 28
