spring:
  application:
    name: music-universe-raw-data-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${MURAW_LASTFM_DB_HOST:localhost}:${MURAW_LASTFM_DB_PORT:9999}/music_universe?currentSchema=mu_raw_lastfm
    username: mu_raw_lastfm_dm
    password: '${MURAW_LASTFM_DB_PASSWORD}'
    hikari:
      pool-name: MuRawLastFmHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        jdbc:
          batch_size: 10
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/migration/muraw/liquibase/db.changelog.xml
  docker:
    compose:
      enabled: false
server:
  port: ${MURAW_LASTFM_PORT:8081}

scheduling:
  lastfm:
    api:
      calls:
        fetch:
          fixedRate: 5000
      responses:
        parse:
          fixedRate: 5000
    tasks:
      tag:
        topTags:
          cron: "0 0 21 * * *"

lastfm:
  baseUrl: "http://ws.audioscrobbler.com/2.0/"
  apikey: ${MURAW_LASTFM_API_KEY}
  client:
    callsPerSec: 1
    retry:
      max-attempts: 3
      initial-delay-ms: 500
      multiplier: 1.5
