spring:
  jpa:
    properties:
      hibernate:
        # Disable schema validation at startup
        javax.persistence.validation.mode: none
  main:
    # Disable Spring Boot banner
    banner-mode: off

# Disable unnecessary auto-configurations
spring.autoconfigure.exclude: >
  org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration,
  org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration,
  org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration,
  org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration,
  org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration,
  org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration

# Limit actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
