plugins {
    id 'art-universe.spring-boot-web-app'
    id 'org.liquibase.gradle'
}

archivesBaseName = 'music-data-master'

dependencies {
    implementation project(':common:commons-web')

    implementation 'org.springframework.boot:spring-boot-docker-compose'

    runtimeOnly 'org.liquibase:liquibase-core'

    testImplementation project(':common:commons-test-web')
    testImplementation project(':common:test:commons-test-db')
}
