spring:
  application:
    name: music-universe-quiz-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${MU_QUIZ_DB_HOST:localhost}:${MU_QUIZ_DB_PORT:5432}/music_universe?currentSchema=mu_quiz
    username: mu_quiz_dm
    password: '${MU_QUIZ_DB_PASSWORD_DM}'
    hikari:
      pool-name: MuQuizHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/migration/muquiz/liquibase/db.changelog.xml
  docker:
    compose:
      enabled: false
server:
  port: ${MU_QUIZ_APP_PORT:8083}
