plugins {
    id 'art-universe.java-base'
    id 'application'
}

archivesBaseName = 'lastfm-liquibase-service'

application {
    mainClass = 'yurykorzun.art.universe.music.data.raw.lastfm.migration.liquibase.LiquibaseMigrationRunner'
}

dependencies {
    implementation 'org.liquibase:liquibase-core'
    runtimeOnly 'org.postgresql:postgresql'
}

tasks.register('copyLiquibaseResources', Copy) {
    from project(':music:data:raw:lastfm:migrations:lastfm-liquibase-resources').file('src/main/resources')
    into "$buildDir/resources/main"
}

processResources {
    dependsOn copyLiquibaseResources
}
