plugins {
    id 'art-universe.spring-boot-web-app'
    id 'org.liquibase.gradle'
}

archivesBaseName = 'lastfm-monolith'

dependencyManagement {
    dependencies {
        dependency 'com.google.guava:guava:33.4.0-jre'
        dependency 'info.debatty:java-string-similarity:2.0.0'
        dependency 'io.hypersistence:hypersistence-utils-hibernate-63:3.9.3'
    }
}

dependencies {
    implementation project(':common:commons-web')
    implementation project(':music:data:raw:lastfm:lastfm-repositories')

    implementation 'org.springframework.boot:spring-boot-docker-compose'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    
    implementation 'com.google.guava:guava'
    implementation 'info.debatty:java-string-similarity'
    implementation 'org.liquibase:liquibase-core'
    implementation 'io.hypersistence:hypersistence-utils-hibernate-63'
    
    testImplementation project(':music:data:raw:lastfm:test:lastfm-commons-test-db-helper')
}
