/**
 * Centralized runtime configuration for API endpoints.
 *
 * In Docker/K8s: reads from window.__APP_CONFIG__ (generated by envsubst at container startup).
 * In local dev (npm run dev): falls back to Vite's import.meta.env.VITE_* from .env file.
 */

interface AppConfig {
    lastfmReadApiHost: string;
    lastfmReadApiPort: string;
    lastfmWriteApiHost: string;
    lastfmWriteApiPort: string;
    musicDataHost: string;
    musicDataPort: string;
    musicQuizHost: string;
    musicQuizPort: string;
    artDataHost: string;
    artDataPort: string;
    configServiceHost: string;
    configServicePort: string;
    authServiceHost: string;
    authServicePort: string;
    googleClientId: string;
}

const runtimeConfig = (window as any).__APP_CONFIG__;

export const appConfig: AppConfig = {
    lastfmReadApiHost: runtimeConfig?.LASTFM_READ_API_HOST || import.meta.env.VITE_MURAW_LASTFM_READ_API_HOST || 'localhost',
    lastfmReadApiPort: runtimeConfig?.LASTFM_READ_API_PORT || import.meta.env.VITE_MURAW_LASTFM_READ_API_EXTERNAL_PORT || '8084',
    lastfmWriteApiHost: runtimeConfig?.LASTFM_WRITE_API_HOST || import.meta.env.VITE_MURAW_LASTFM_WRITE_API_HOST || 'localhost',
    lastfmWriteApiPort: runtimeConfig?.LASTFM_WRITE_API_PORT || import.meta.env.VITE_MURAW_LASTFM_WRITE_API_EXTERNAL_PORT || '8085',
    musicDataHost: runtimeConfig?.MUSIC_DATA_HOST || import.meta.env.VITE_MU_DATA_APP_HOST || 'localhost',
    musicDataPort: runtimeConfig?.MUSIC_DATA_PORT || import.meta.env.VITE_MU_DATA_APP_EXTERNAL_PORT || '8082',
    musicQuizHost: runtimeConfig?.MUSIC_QUIZ_HOST || import.meta.env.VITE_MU_QUIZ_APP_HOST || 'localhost',
    musicQuizPort: runtimeConfig?.MUSIC_QUIZ_PORT || import.meta.env.VITE_MU_QUIZ_APP_EXTERNAL_PORT || '8083',
    artDataHost: runtimeConfig?.ART_DATA_HOST || import.meta.env.VITE_ART_DATA_APP_HOST || 'localhost',
    artDataPort: runtimeConfig?.ART_DATA_PORT || import.meta.env.VITE_ART_DATA_APP_EXTERNAL_PORT || '8081',
    configServiceHost: runtimeConfig?.CONFIG_SERVICE_HOST || import.meta.env.VITE_AU_CONFIG_APP_HOST || 'localhost',
    configServicePort: runtimeConfig?.CONFIG_SERVICE_PORT || import.meta.env.VITE_AU_CONFIG_APP_EXTERNAL_PORT || '8070',
    authServiceHost: runtimeConfig?.AUTH_SERVICE_HOST || import.meta.env.VITE_AU_AUTH_APP_HOST || 'localhost',
    authServicePort: runtimeConfig?.AUTH_SERVICE_PORT || import.meta.env.VITE_AU_AUTH_APP_EXTERNAL_PORT || '8071',
    googleClientId: runtimeConfig?.GOOGLE_CLIENT_ID || import.meta.env.VITE_GOOGLE_CLIENT_ID || '',
};
