plugins {
    id 'art-universe.spring-boot-web-app'
}

archivesBaseName = 'semantic-analyzer'

dependencies {
    implementation project(':common:commons-web')
    implementation project(':common:commons-observability')
    implementation project(':common:commons-pg-notify')
    implementation project(':common:config:config-client')
    implementation project(':common:data:raw:data-raw-commons-api-client')
    implementation project(':music:data:semantic:semantic-models')
}
