plugins {
    id 'art-universe.java-library'
}

archivesBaseName = 'spotify-commons-test-db'

dependencies {
    api project(':music:data:raw:spotify:migrations:spotify-liquibase-resources')
    api project(':common:test:commons-test-db')
    api project(':common:config:config-client')

    api 'org.springframework.boot:spring-boot-starter-test'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-test-autoconfigure'
    api 'org.springframework:spring-context'
    api 'org.springframework:spring-test'
    api 'org.springframework:spring-tx'
    api 'org.testcontainers:junit-jupiter'
    api 'org.testcontainers:postgresql'

    implementation 'org.slf4j:slf4j-api'
    implementation 'org.springframework.boot:spring-boot-test'
    implementation 'org.springframework:spring-core'
    implementation 'org.testcontainers:testcontainers'
    implementation 'org.testcontainers:jdbc'

    runtimeOnly 'org.liquibase:liquibase-core'
}
