plugins {
    id 'art-universe.spring-boot-app'
}

dependencies {
    implementation project(':music:data:raw:lastfm:models')
    
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'
    
    implementation 'com.google.guava:guava:33.4.0-jre'
    implementation 'info.debatty:java-string-similarity:2.0.0'
    implementation 'io.micrometer:micrometer-registry-prometheus'
}

// disable until migration is finished
tasks.named('bootJar') {
    enabled = false
}
tasks.named('extractLayers') {
     enabled = false
}