plugins {
    id 'io.spring.dependency-management'
}

tasks.matching { it.name == 'jar' }.configureEach { enabled = true }

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}

dependencies {
    // persistence
    implementation 'org.springframework.data:spring-data-jpa'
    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // HTTP-client
    implementation 'org.springframework:spring-web'
    
    // reflection
    implementation 'org.reflections:reflections:0.10.2'
}
