plugins {
    id 'art-universe.spring-boot-web-app'
}

archivesBaseName = 'semantic-response-parser'

dependencies {
    implementation project(':common:commons-web')
    implementation project(':common:commons-observability')
    implementation project(':common:commons-pg-notify')
    implementation project(':common:config:config-client')
    implementation project(':music:data:semantic:semantic-models')

    implementation 'org.springframework.boot:spring-boot-docker-compose'
}
