version: '3.8'

services:
  postgres:
    container_name: dev__mu-data__db-postgres
    restart: unless-stopped
    shm_size: 128mb
    stop_grace_period: 1m
    stop_signal: SIGINT
    build:
      dockerfile: ../common/postgres.dockerfile
      context: ../common
    env_file:
      - ${PROJECT_ROOT}/env/docker/local/music-data.env
      - ${PROJECT_ROOT}/env/docker/local/music-data.secrets.env
      - ${PROJECT_ROOT}/env/docker/local/music-quiz.env
      - ${PROJECT_ROOT}/env/docker/local/music-quiz.secrets.env
      - ${PROJECT_ROOT}/music/data/master/dev.override.env
      - ${PROJECT_ROOT}/music/quiz/dev.override.env
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
      - ../common/initdb/templates:/docker-entrypoint-initdb.d
    command: bash -c "envsubst < /docker-entrypoint-initdb.d/init.sql.template > /docker-entrypoint-initdb.d/init.sql && exec docker-entrypoint.sh postgres"
    ports:
      - "${MU_DATA_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-adminer:
    container_name: dev__mu-data__db-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "${DB_ADMINER_PORT}:8080"

networks:
  default:
    name: dev__mu-shared-network

volumes:
  db-postgres-data:
    name: dev__mu-data__db-postgres-data
